#!/bin/bash
/home/tom/work/BiscuitOS-ALL/BiscuitOS/output/linux-4.14.1-aarch/linux/linux-4.14.1-1/arch/arm64/boot/dts/qemu/dtc -O dtb -o /home/tom/work/BiscuitOS-ALL/BiscuitOS/output/linux-4.14.1-aarch/linux/linux-4.14.1-1/arch/arm64/boot/dts/qemu/qemu-a53.dtb /home/tom/work/BiscuitOS-ALL/BiscuitOS/output/linux-4.14.1-aarch/linux/linux-4.14.1-1/arch/arm64/boot/dts/qemu/qemu-a53.dts
cp /home/tom/work/BiscuitOS-ALL/BiscuitOS/output/linux-4.14.1-aarch/linux/linux-4.14.1-1/arch/arm64/boot/dts/qemu/qemu-a53.dtb /home/tom/work/BiscuitOS-ALL/BiscuitOS/output/linux-4.14.1-aarch/linux/out
